### ISSUE TITLE
output file size for low resolution site

### ISSUE THREAD

**Issue by kb0thn** [aprsworld/TimeLapse#3]
I encoded a week of data from office1 camera. It was 640x498 photo size. Time lapse took as long to encode as a site with bigger photos. And the resulting time lapse file size was basically the same.

Note: office1 site is now sending higher resolution photos. But 2015-05-29 and earlier would be the 640x498

**Comment by davarus** [comment]
Just looking at office1/2015/05/01, it is taking snapshots way more often than the original deepLake site I used at which would account for the discrepancy.  So instead of n frames it has 4n frames.  When issue #1 is implemented properly I will re-look into this issue to ensure that is the discrepancy.  Leaving open even though it's likely nothing.

**Comment by davarus** [comment]
Confirmed non-issue in commit aa28b03ddfd82be9cc714ce16d45c131912822db.
